case = "SrVO3"

[dft]
engine = "vasp"
niter = 100
lortho = true
lspinorb = false
lproj = false
nproj = 1
sproj = ["P1"]

[dmft]
niter = 1
dcount = 1
nominal = 3.0

[solver]
engine = "ct_hub1"
params = []

[impurity]
nimp = 1
atoms = ["V"]
equiv = [[1]]
shell = ["d"]
ising = [true]
upara = [4.0]
jpara = [0.7]
lpara = [0.0]

[dft_dmft]
axis = 1
beta = 40.0
niter = 60
mixer = 0.5
cc = 1.0E-4
ec = 1.0E-4
fc = 1.0E-4
lforce = false
lcharge = true
lenergy = true
