case = "FeSe"

[dft]
engine = "vasp"
smear = "m-p"
kmesh = "medium"
lsymm = true
lspins = false
lspinorb = false
window = [6.0, 9.0]
loptim = false
lproj = true
nproj = 2
sproj = ["1 : d : Pr", "2 : d : Pr"]

[dmft]
mode = 1
axis = 1
beta = 40.0
niter = 60
mixer = 0.5
dcount = "fll1"

[impurity]
nsite = 2
atoms = ["Fe", "Fe"]
equiv = [[1, 2]]
shell = ["d", "d"]
ising = ["true", "true"]
occup = [6.0, 6.0]
upara = [5.0, 5.0]
jpara = [0.8, 0.8]
lpara = [0.0, 0.0]

[solver]
engine = "ct_hub1"
params = [""]

cc = 1.0E-4
ec = 1.0E-4
fc = 1.0E-4
lforce = false
lcharge = true
lenergy = true
