case = "Ce"

[dft]
engine = "vasp"
lspins = false
lspinorb = true

[dft.adaptor]
lortho = true

[dft.projector]
lproj = true
nproj = 1
sproj = ["1 : f : Pr"]

[dmft]
dcount = 1
nominal = 1.0

[dmft.impurity]
nimp = 1
atoms = ["Ce"]
equiv = [[1]]
shell = ["f"]
ising = [false]
upara = [6.0]
jpara = [0.7]
lpara = [0.0]

[dmft.solver]
engine = "ct_hub1"
params = []

[dft_dmft]
mode = 1
axis = 1
beta = 40.0
niter = 60
mixer = 0.5
cc = 1.0E-4
ec = 1.0E-4
fc = 1.0E-4
lforce = false
lcharge = true
lenergy = true
