case = "FeSe"

[dft]
engine = "vasp"
smear = "m-p"
kmesh = "medium"
lsymm = false
lspins = false
lspinorb = false
loptim = false
window = [6.0, 9.0]
lproj = true
sproj = ["1 : d : Pr", "2 : d : Pr"]

[dmft]
mode = 1
axis = 1
beta = 40.0
niter = 60
mixer = 0.5
dcount = "fll1"
cc = 1.0E-4
ec = 1.0E-4
fc = 1.0E-4
lcharge = true
lenergy = true
lforce = false

[impurity]
nsite = 2
atoms = ["Fe : 1", "Fe : 2"]
equiv = [1, 1]
shell = ["d", "d"]
ising = ["ising", "ising"]
occup = [6.0, 6.0]
upara = [5.0, 5.0]
jpara = [0.8, 0.8]
lpara = [0.0, 0.0]

[solver]
engine = "ct_hub1"
params = [""]
